# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: git.rss.iste.uni-stuttgart.de:5050/pse/pipeline-test/opencv

build:
    stage: build
    script:
        - cmake .
        - cmake --build .

test:
    stage: test
    script:
        - ctest

checkFormat:
    stage: test
    script:
        - clang-format src/* -n -Werror

findMemleaks:
    stage: test
    script:
        - valgrind --leak-check=yes myprog

deployDoc:
    stage: test
    script:
        - doxygen
    artifacts:
        paths:
            - generated_doc/latex/*.pdf
            - generated_doc/html/*
        expire_in: 2 days