image: debian:unstable

build:
    stage: build
    before_script:
        - cat /proc/self/cgroup
    script:
        - ( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && cmake . )
        - ( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && cmake --build . )
    artifacts:
        untracked: true
        expire_in: 1 hrs

test:
    stage: test
    dependencies: 
        - build
    script:
        - ctest

checkFormat:
    stage: test
    script:
        - clang-format src/* -n -Werror
        - clang-format include/* -n -Werror
        - clang-format test/* -n -Werror

findMemleaks:
    stage: test
    dependencies: 
        - build
    script:
        - valgrind --leak-check=yes ./OpenCVTests
        - valgrind --leak-check=yes ./OpenCVDemo noGui

deployDoc:
    stage: test
    script:
        - doxygen
        - cd generated_doc/latex && make
    artifacts:
        paths:
            - generated_doc/latex/*.pdf
            - generated_doc/html/*
        expire_in: 2 days