#image: debian:unstable

buildLinux:
    stage: build
    tags:
        - ubuntu-20.04
    before_script:
        - cat /proc/self/cgroup
    script:
        - cmake .
        - cmake --build .
    artifacts:
        untracked: true
        expire_in: 1 hrs

testLinux:
    stage: test
    before_script:
        - cat /proc/self/cgroup
    tags:
        - ubuntu-20.04
    dependencies: 
        - buildLinux
    script:
        - ctest

checkFormat:
    stage: test
    before_script:
        - cat /proc/self/cgroup
    tags:
        - ubuntu-20.04
    script:
        - clang-format src/* -n -Werror
        - clang-format include/* -n -Werror
        - clang-format test/* -n -Werror

findMemleaksLinux:
    stage: test
    before_script:
        - cat /proc/self/cgroup
    tags:
        - ubuntu-20.04
    dependencies: 
        - buildLinux
    script:
        - valgrind --leak-check=yes ./OpenCVTests
        - valgrind --leak-check=yes ./OpenCVDemo noGui

deployDoc:
    stage: test
    before_script:
        - cat /proc/self/cgroup
    tags:
        - ubuntu-20.04
    script:
        - doxygen
        - cd generated_doc/latex && make
    artifacts:
        paths:
            - generated_doc/latex/*.pdf
            - generated_doc/html/*
        expire_in: 2 days