#image: debian:unstable

buildLinux:
    stage: build
    tags:
        - ubuntu-20.04
    script:
        -  ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && cmake . )
        -  ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && cmake --build . )
    artifacts:
        untracked: true
        expire_in: 1 hrs

testLinux:
    stage: test
    tags:
        - ubuntu-20.04
    dependencies: 
        - buildLinux
    script:
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && ctest )

checkFormat:
    stage: test
    tags:
        - ubuntu-20.04
    script:
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && clang-format src/* -n -Werror )
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && clang-format include/* -n -Werror )
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && clang-format test/* -n -Werror )

findMemleaksLinux:
    stage: test
    tags:
        - ubuntu-20.04
    dependencies: 
        - buildLinux
    script:
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && valgrind --leak-check=yes --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./OpenCVTests )
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && valgrind --leak-check=yes --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./OpenCVDemo noGui )

deployDoc:
    stage: test
    tags:
        - ubuntu-20.04
    script:
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && doxygen )
        - ( trap 'echo WorkingAround; sleep 1; echo end' EXIT && cd generated_doc/latex && make )
    artifacts:
        paths:
            - generated_doc/latex/*.pdf
            - generated_doc/html/*
        expire_in: 2 days

buildWindows:
    stage: build
    tags:
        - windows-10
    script:
        - cmake .
        - cmake --build .
    artifacts:
        untracked: true
        expire_in: 1 hrs

testWindows:
    stage: test
    tags:
        - windows-10
    dependencies: 
        - buildWindows
    script:
        - ctest