build:
    tags: [ubuntu-20.04]
    stage: build
    script:
        - cmake .
        - cmake --build .
    artifacts:
        untracked: true
        expire_in: 1 hrs

test:
    tags: [ubuntu-20.04]
    stage: test
    dependencies: 
        - build
    script:
        - ctest

checkFormat:
    tags: [ubuntu-20.04]
    stage: test
    script:
        - clang-format src/* -n -Werror
        - clang-format include/* -n -Werror
        - clang-format test/* -n -Werror

findMemleaks:
    tags: [ubuntu-20.04]
    stage: test
    dependencies: 
        - build
    script:
        - valgrind --leak-check=yes ./OpenCVTests
        - valgrind --leak-check=yes ./OpenCVDemo noGui

deployDoc:
    tags: [ubuntu-20.04]
    stage: test
    script:
        - doxygen
        - cd generated_doc/latex && make
    artifacts:
        paths:
            - generated_doc/latex/*.pdf
            - generated_doc/html/*
        expire_in: 2 days
