FROM debian:unstable

RUN apt-get update && apt-get -y install make g++ gcc autoconf cmake libopencv-*-dev clang-format valgrind doxygen pandoc texlive-latex-base texlive-latex-extra texlive-latex-recommended